import type { Account, Business, BusinessType, ISODate, Subscription, User, WorkspaceData } from "../types";
import { addDays, instantOn } from "../utils/date";
import { createId } from "../utils/id";
import { createContext } from "../domain/context";
import { addQuote } from "../domain/quotes";
import { runAutomation } from "../domain/automation";
import { markLost, markReplied, markWon, pauseQuote } from "../domain/status";
import type { PlatformAccount } from "../metrics";
import { DEMO_SERVICES } from "./services";

/**
 * Demo data is generated by replaying real domain operations day by day, so
 * every timeline, follow-up count and status is exactly what the automation
 * engine would have produced. Quotes are flagged `isDemo` so they can be
 * cleared in Settings.
 */

interface DemoScript {
  customer: { name: string; email: string; phone: string | null };
  serviceIndex: number;
  amount: number;
  sentDaysAgo: number;
  /** What happened on which day (relative to sent date). Omit for still-active quotes. */
  outcome?: { type: "replied" | "won" | "lost" | "paused"; onDay: number; thenWonOnDay?: number };
  schedule?: number[];
  notes?: string;
}

const SCRIPTS: DemoScript[] = [
  {
    customer: { name: "Sarah Mitchell", email: "sarah.mitchell@example.com", phone: "(555) 201-4471" },
    serviceIndex: 0,
    amount: 2850,
    sentDaysAgo: 3,
    notes: "Wants it done before Thanksgiving. Prefers neutral colors.",
  },
  {
    customer: { name: "Tom Alvarez", email: "tom.alvarez@example.com", phone: "(555) 318-9902" },
    serviceIndex: 1,
    amount: 6400,
    sentDaysAgo: 1,
  },
  {
    customer: { name: "Priya Natarajan", email: "priya.n@example.com", phone: null },
    serviceIndex: 2,
    amount: 3200,
    sentDaysAgo: 6,
    outcome: { type: "replied", onDay: 3 },
    notes: "Asked about a weekend start.",
  },
  {
    customer: { name: "Daniel Okafor", email: "daniel.okafor@example.com", phone: "(555) 772-0034" },
    serviceIndex: 3,
    amount: 1150,
    sentDaysAgo: 14,
    outcome: { type: "won", onDay: 6 },
  },
  {
    customer: { name: "Emily Chen", email: "emily.chen@example.com", phone: null },
    serviceIndex: 4,
    amount: 1975,
    sentDaysAgo: 18,
    outcome: { type: "lost", onDay: 12 },
    notes: "Went with a cheaper quote.",
  },
  {
    customer: { name: "Marcus Reed", email: "marcus.reed@example.com", phone: "(555) 640-2210" },
    serviceIndex: 5,
    amount: 2600,
    sentDaysAgo: 4,
    outcome: { type: "paused", onDay: 3 },
    notes: "Traveling until the end of the month. Asked us to hold off.",
  },
  {
    customer: { name: "Linda Park", email: "linda.park@example.com", phone: "(555) 905-1188" },
    serviceIndex: 6,
    amount: 2300,
    sentDaysAgo: 12,
  },
  {
    customer: { name: "Jorge Ramirez", email: "jorge.ramirez@example.com", phone: null },
    serviceIndex: 7,
    amount: 1400,
    sentDaysAgo: 7,
  },
  {
    customer: { name: "Hannah Brooks", email: "hannah.brooks@example.com", phone: "(555) 412-7760" },
    serviceIndex: 8,
    amount: 7900,
    sentDaysAgo: 20,
    outcome: { type: "replied", onDay: 6, thenWonOnDay: 8 },
    notes: "Referred by the Okafors.",
  },
  {
    customer: { name: "Kevin O'Neil", email: "kevin.oneil@example.com", phone: "(555) 233-8817" },
    serviceIndex: 9,
    amount: 980,
    sentDaysAgo: 0,
    schedule: [1, 3, 7],
  },
  {
    customer: { name: "Aisha Rahman", email: "aisha.rahman@example.com", phone: null },
    serviceIndex: 0,
    amount: 4250,
    sentDaysAgo: 9,
    outcome: { type: "won", onDay: 9 },
  },
  {
    customer: { name: "Robert Lindqvist", email: "robert.l@example.com", phone: "(555) 118-4402" },
    serviceIndex: 3,
    amount: 1650,
    sentDaysAgo: 2,
  },
];

const EMPTY: WorkspaceData = { customers: [], quotes: [], followUps: [], timeline: [], inbound: [] };

function quoteNumber(index: number, today: ISODate): string {
  const year = today.slice(0, 4);
  return `EST-${year}-${String(1040 + index).padStart(4, "0")}`;
}

export function buildDemoWorkspace(account: Account, today: ISODate): WorkspaceData {
  const services = DEMO_SERVICES[account.business.type] ?? DEMO_SERVICES.other;
  let data = EMPTY;

  SCRIPTS.forEach((script, index) => {
    const sentAt = addDays(today, -script.sentDaysAgo);
    const schedule = script.schedule ?? account.settings.defaultSchedule;
    const startCtx = createContext(account.business, account.settings, sentAt);

    const added = addQuote(
      data,
      {
        customerName: script.customer.name,
        customerEmail: script.customer.email,
        customerPhone: script.customer.phone ?? "",
        quoteNumber: quoteNumber(index, today),
        serviceDescription: services[script.serviceIndex % services.length],
        amount: script.amount,
        sentAt,
        notes: script.notes ?? "",
        schedule,
        tone: account.settings.defaultTone,
      },
      startCtx,
      { isDemo: true },
    );
    data = added.data;
    const quoteId = added.quote.id;

    // Replay each day since the quote was sent.
    for (let day = 0; day <= script.sentDaysAgo; day += 1) {
      const date = addDays(sentAt, day);
      const ctx = createContext(account.business, account.settings, date);

      if (script.outcome && script.outcome.onDay === day) {
        if (script.outcome.type === "replied") data = markReplied(data, quoteId, ctx);
        if (script.outcome.type === "won") data = markWon(data, quoteId, ctx);
        if (script.outcome.type === "lost") data = markLost(data, quoteId, ctx);
        if (script.outcome.type === "paused") data = pauseQuote(data, quoteId, ctx);
      }
      if (script.outcome?.thenWonOnDay === day) {
        data = markWon(data, quoteId, ctx);
      }

      data = runAutomation(data, ctx).data;
    }
  });

  return data;
}

interface DemoAccountSpec {
  business: string;
  owner: string;
  type: BusinessType;
  plan: Subscription["plan"];
  status: Subscription["status"];
  daysAgo: number;
}

const DEMO_ACCOUNTS: DemoAccountSpec[] = [
  { business: "Northside Painting Co.", owner: "Mike Turner", type: "painting", plan: "starter", status: "active", daysAgo: 61 },
  { business: "ClearFlow Pressure Washing", owner: "Dana Whitfield", type: "pressure_washing", plan: "pro", status: "active", daysAgo: 45 },
  { business: "Greenline Landscapes", owner: "Luis Herrera", type: "landscaping", plan: "starter", status: "active", daysAgo: 30 },
  { business: "BrightNest Cleaning", owner: "Amara Osei", type: "cleaning", plan: "trial", status: "trialing", daysAgo: 6 },
  { business: "Summit Roofing", owner: "Chris Bauer", type: "roofing", plan: "pro", status: "active", daysAgo: 22 },
  { business: "Harbor Pool Care", owner: "Nina Castellano", type: "pool", plan: "trial", status: "trialing", daysAgo: 3 },
  { business: "Keystone Handyman", owner: "Pat Delaney", type: "handyman", plan: "starter", status: "cancelled", daysAgo: 90 },
  { business: "Volt Electric", owner: "Sam Okoro", type: "electrical", plan: "trial", status: "trialing", daysAgo: 1 },
];

/** Fictional other accounts so the owner admin view has something to show. */
export function buildDemoPlatformAccounts(today: ISODate): PlatformAccount[] {
  return DEMO_ACCOUNTS.map((spec) => {
    const createdAt = instantOn(addDays(today, -spec.daysAgo));
    const user: User = {
      id: createId("user"),
      name: spec.owner,
      email: `${spec.owner.toLowerCase().replace(/\s+/g, ".")}@example.com`,
      createdAt,
    };
    const business: Business = {
      id: createId("biz"),
      ownerUserId: user.id,
      name: spec.business,
      ownerName: spec.owner,
      email: user.email,
      type: spec.type,
      createdAt,
    };
    const subscription: Subscription = {
      id: createId("sub"),
      businessId: business.id,
      plan: spec.plan,
      status: spec.status,
      stripeCustomerId: null,
      stripeSubscriptionId: null,
      trialEndsAt: spec.status === "trialing" ? instantOn(addDays(today, 14 - spec.daysAgo)) : null,
      createdAt,
    };
    return { user, business, subscription };
  });
}
