import type { BusinessType } from "../types";

/** Realistic service descriptions per trade so demo data matches the user's business. */
export const DEMO_SERVICES: Record<BusinessType, string[]> = {
  painting: [
    "Interior painting, 3 bedrooms and hallway",
    "Exterior repaint, two-story colonial",
    "Kitchen cabinet refinishing",
    "Deck staining and sealing",
    "Trim and door painting, whole house",
    "Garage floor epoxy coating",
    "Accent wall and ceiling repaint",
    "Fence painting, 120 linear feet",
    "Living room and dining room repaint",
    "Bathroom repaint with mildew-resistant finish",
  ],
  pressure_washing: [
    "House wash, two-story vinyl siding",
    "Driveway and walkway pressure wash",
    "Deck cleaning and brightening",
    "Roof soft wash, asphalt shingle",
    "Commercial storefront wash",
    "Fence cleaning, 150 linear feet",
    "Pool deck and patio wash",
    "Gutter exterior brightening",
    "Concrete sealing after wash",
    "Paver cleaning and re-sanding",
  ],
  landscaping: [
    "Front yard landscape redesign",
    "Sod installation, 2,400 sq ft",
    "Weekly lawn maintenance, season contract",
    "Mulch delivery and bed refresh",
    "Paver patio installation",
    "Irrigation system repair",
    "Tree and shrub trimming",
    "Retaining wall, 40 linear feet",
    "Fall cleanup and leaf removal",
    "Drainage correction, side yard",
  ],
  cleaning: [
    "Deep clean, 4-bedroom home",
    "Move-out cleaning, 2-bed apartment",
    "Bi-weekly recurring house cleaning",
    "Post-renovation cleanup",
    "Office cleaning, 3,000 sq ft",
    "Carpet cleaning, 5 rooms",
    "Window cleaning, interior and exterior",
    "Airbnb turnover cleaning",
    "Oven and refrigerator detail",
    "Garage and basement cleanout",
  ],
  pool: [
    "Pool opening and startup",
    "Weekly pool service, summer contract",
    "Pump and filter replacement",
    "Pool heater installation",
    "Green pool recovery",
    "Tile cleaning and calcium removal",
    "Salt system conversion",
    "Pool closing and winterization",
    "Leak detection and repair",
    "Automatic cleaner installation",
  ],
  roofing: [
    "Roof replacement, architectural shingles",
    "Roof repair, storm damage",
    "Gutter replacement, seamless aluminum",
    "Skylight replacement",
    "Chimney flashing repair",
    "Metal roof installation, detached garage",
    "Attic ventilation upgrade",
    "Roof inspection and tune-up",
    "Flat roof recoat",
    "Soffit and fascia repair",
  ],
  handyman: [
    "Drywall repair and paint touch-up",
    "Ceiling fan installation, 3 rooms",
    "Bathroom faucet and vanity replacement",
    "Deck board replacement",
    "Interior door hanging, 4 doors",
    "TV mounting and cable concealment",
    "Shelving and closet organizer install",
    "Weatherstripping and caulking",
    "Fence gate repair",
    "Smart lock and doorbell installation",
  ],
  flooring: [
    "Luxury vinyl plank, 900 sq ft",
    "Hardwood refinishing, main floor",
    "Tile installation, master bathroom",
    "Carpet replacement, 3 bedrooms",
    "Laminate flooring, basement",
    "Stair tread replacement",
    "Engineered hardwood, living room",
    "Subfloor repair and leveling",
    "Kitchen tile backsplash",
    "Baseboard and transition install",
  ],
  hvac: [
    "AC replacement, 3-ton system",
    "Furnace replacement, 80k BTU",
    "Ductless mini-split, 2 zones",
    "Duct cleaning and sealing",
    "Thermostat upgrade and zoning",
    "Heat pump installation",
    "Annual maintenance agreement",
    "Blower motor replacement",
    "Humidifier installation",
    "Refrigerant leak repair",
  ],
  plumbing: [
    "Water heater replacement, 50 gal",
    "Kitchen sink and disposal install",
    "Main line drain cleaning",
    "Bathroom remodel rough-in",
    "Sump pump replacement",
    "Whole-house water filtration",
    "Toilet replacement, 2 bathrooms",
    "Gas line for outdoor grill",
    "Leak repair under slab",
    "Tankless water heater install",
  ],
  electrical: [
    "Panel upgrade, 200 amp",
    "EV charger installation",
    "Recessed lighting, kitchen and living room",
    "Whole-house generator install",
    "Outdoor landscape lighting",
    "Ceiling fan and dimmer install",
    "Hot tub circuit",
    "Basement finish wiring",
    "Smoke and CO detector replacement",
    "Outlet and GFCI upgrades",
  ],
  remodeling: [
    "Kitchen remodel, mid-range",
    "Master bathroom remodel",
    "Basement finish, 800 sq ft",
    "Deck build, 16x20 composite",
    "Mudroom addition",
    "Garage conversion to office",
    "Hall bath refresh",
    "Open-concept wall removal",
    "Laundry room renovation",
    "Screened porch build",
  ],
  other: [
    "Service visit and repair",
    "Installation, standard package",
    "Seasonal maintenance plan",
    "Full replacement",
    "Inspection and tune-up",
    "Premium package install",
    "Repair, parts and labor",
    "Annual service agreement",
    "Emergency repair",
    "Upgrade and reconfiguration",
  ],
};
